SookmyungTackit/backend

src/main/java/org/example/tackit/config/AdminDataInitializer.java, src/main/java/org/example/tackit/config/SecurityConfig.java
> #10 
* 관리자 api 허용
* 관리자 계정 등록 (AdminDataInitializer.java)
=> [FEAT] 관리자 로그인 구현

src/main/java/org/example/tackit/domain/QnA_post/controller/QnAPostController.java, src/main/java/org/example/tackit/domain/QnA_post/dto/request/QnAPostRequestDto.java, src/main/java/org/example/tackit/domain/QnA_post/dto/request/UpdateQnARequestDto.java, src/main/java/org/example/tackit/domain/QnA_post/dto/response/QnAPostResponseDto.java, src/main/java/org/example/tackit/domain/QnA_post/repository/QnAMemberRepository.java, src/main/java/org/example/tackit/domain/QnA_post/repository/QnAPostRepository.java, src/main/java/org/example/tackit/domain/QnA_post/service/QnAPostService.java, src/main/java/org/example/tackit/domain/entity/QnAPost.java
> #17 
* 질문게시판 기본 CRUD 구현 (NEWBIE 기준)
* **role=NEWBIE**는 질문 게시글만 가능
* 글 작성, 수정, 삭제, 전체 조회, 상세 조회
=> [FEAT] 질문게시판 CRUD - 신입 게시글

src/main/java/org/example/tackit/domain/QnA_comment/controller/QnACommentController.java, src/main/java/org/example/tackit/domain/QnA_comment/dto/request/QnACommentCreateDto.java, src/main/java/org/example/tackit/domain/QnA_comment/dto/request/QnACommentUpdateDto.java, src/main/java/org/example/tackit/domain/QnA_comment/dto/response/QnACommentResponseDto.java, src/main/java/org/example/tackit/domain/QnA_comment/repository/QnACommentRepository.java, src/main/java/org/example/tackit/domain/QnA_comment/service/QnACommentService.java, src/main/java/org/example/tackit/domain/QnA_post/dto/request/QnAPostCreateDto.java, src/main/java/org/example/tackit/domain/QnA_post/dto/request/QnAPostUpdateDto.java, src/main/java/org/example/tackit/domain/QnA_post/repository/QnAMemberRepository.java, src/main/java/org/example/tackit/domain/entity/QnAComment.java
> #20 
* 선배 댓글 CRUD
* userdetail로 회원정보 확인 (게시글 로직과 동일)
=> [FEAT] 질문게시판 답변 CRUD-선배댓글

src/main/java/org/example/tackit/domain/QnA_post/dto/request/QnAPostRequestDto.java, src/main/java/org/example/tackit/domain/QnA_post/dto/request/UpdateQnARequestDto.java
> #20
* QnA request Dto 이름 변경 
* `QnAPostRequestDto` , `UpdateQnARequestDto`
=> [RENAME] DTO 이름 변경

src/main/java/org/example/tackit/domain/QnA_board/QnA_comment/repository/QnACommentRepository.java, src/main/java/org/example/tackit/domain/QnA_board/QnA_post/repository/QnAPostRepository.java, src/main/java/org/example/tackit/domain/auth/logout/repository/LogoutRepository.java, src/main/java/org/example/tackit/domain/mypage/controller/MemberController.java, src/main/java/org/example/tackit/domain/mypage/controller/MypageQnAController.java, src/main/java/org/example/tackit/domain/mypage/dto/response/QnAMyCommentResponseDto.java, src/main/java/org/example/tackit/domain/mypage/dto/response/QnAMyPostResponseDto.java, src/main/java/org/example/tackit/domain/mypage/repository/MemberDetailRepository.java, src/main/java/org/example/tackit/domain/mypage/service/MyPageQnAService.java
> #32
* 질문게시판 본인이 작성한 게시글 확인 api - NEWBIE
* 질문게시판 본인이 작성한 댓글 확인 api - SENIOR
=> [FEAT] 질문게시판 본인 작성 글 확인

src/main/java/org/example/tackit/domain/QnA_board/QnA_post/dto/response/QnAPostResponseDto.java, src/main/java/org/example/tackit/domain/QnA_board/QnA_post/service/QnAPostService.java
> #42
* 게시글 Id 같이 response
* 게시글 생성, 수정, 전체 조회, 상세 조회
=> [FEAT] 질문게시판 게시글, 댓글 Id 같이 response

src/main/java/org/example/tackit/domain/QnA_board/QnA_comment/service/QnACommentService.java, src/main/java/org/example/tackit/domain/QnA_board/QnA_post/service/QnAPostService.java, src/main/java/org/example/tackit/domain/entity/QnAComment.java
> #47
* 질문 ) 작성자만 게시글 수정
* 질문 ) 작성자만 댓글 수정
* 3회 이상 신고 댓글-> hard delete
=> [FEAT] 작성자만 게시글, 댓글 수정

src/main/java/org/example/tackit/domain/Free_board/Free_post/dto/response/FreePostDTO.java, src/main/java/org/example/tackit/domain/Free_board/Free_post/repository/FreePostJPARepository.java, src/main/java/org/example/tackit/domain/entity/FreePost.java, src/main/java/org/example/tackit/domain/mypage/controller/MypageFreeController.java, src/main/java/org/example/tackit/domain/mypage/dto/response/FreeMyPostResponseDto.java, src/main/java/org/example/tackit/domain/mypage/service/MyPageFreeService.java
>#60
* 작성한 **자유** 게시글 페이징
* FreePost 엔티티 필드 `user_id` -> `member_id`로 변환
=> feat:#60-free) 작성 게시글 페이징

build.gradle, src/main/java/org/example/tackit/domain/admin/controller/AdminPostController.java, src/main/java/org/example/tackit/domain/admin/repository/AdminFreePostRepository.java, src/main/java/org/example/tackit/domain/admin/repository/AdminQnAPostRepository.java, src/main/java/org/example/tackit/domain/admin/repository/AdminTipPostRepository.java, src/main/java/org/example/tackit/domain/admin/service/AdminFreePostService.java, src/main/java/org/example/tackit/domain/admin/service/AdminQnAPostService.java, src/main/java/org/example/tackit/domain/admin/service/AdminTipPostService.java, src/main/java/org/example/tackit/domain/admin/service/ReportedPostService.java, src/main/java/org/example/tackit/global/dto/PageResponseDTO.java
>#65
* 신고되어 비활성화된 게시글 페이징
* Free 게시글
* Tip 게시글
* QnA 게시글
=> [FEAT] 관리자 ) 신고된 비활성화 게시글 페이징

src/main/java/org/example/tackit/domain/Tip_board/repository/TipPostJPARepository.java, src/main/java/org/example/tackit/domain/mypage/controller/MypageTipController.java, src/main/java/org/example/tackit/domain/mypage/dto/response/TipMyPostResponseDto.java, src/main/java/org/example/tackit/domain/mypage/service/MyPageTipService.java
=> [FEAT] Tip ) 작성 게시글 페이징

src/main/java/org/example/tackit/domain/Free_board/Free_comment/repository/FreeCommentRepository.java, src/main/java/org/example/tackit/domain/Free_board/Free_comment/service/FreeCommentService.java, src/main/java/org/example/tackit/domain/mypage/controller/MypageFreeController.java, src/main/java/org/example/tackit/domain/mypage/dto/response/FreeMyCommentResponseDto.java, src/main/java/org/example/tackit/domain/mypage/service/MyPageFreeService.java
> #60
* 마이페이지 - 내가 작성한 자유 게시글의 댓글을 페이징하여 조회
=> [FEAT] Free ) 작성 댓글 페이징

src/main/java/org/example/tackit/domain/admin/dto/ReportedPostDTO.java
> #71 
* 관리자 ) 신고되어 비활성화된 게시글 조회 시 postId 값 추가하여 반환
=> [REFACTOR] 신고 게시글 조회 시 postId 값 반환

build.gradle, src/main/resources/application.properties
>#78
* build.gradle ) spring actuator, prometheus 설정 추가
* application.properties ) actuator 설정 추가
=> [CHORE] : Spring Actuator 설정 추가

src/main/java/org/example/tackit/config/SecurityConfig.java
> #80
* 스프링 시큐리티 url에 actuator 설정
=> [CHORE] Security에 actuator 경로 설정

src/main/java/org/example/tackit/domain/QnA_board/QnA_post/controller/QnAPostController.java, src/main/java/org/example/tackit/domain/QnA_board/QnA_post/repository/QnAPostReportRepository.java, src/main/java/org/example/tackit/domain/QnA_board/QnA_post/service/QnAPostService.java
>#84
* 질문 게시글 신고하기 한사람당 한번만 가능하게 수정
=> [REFACTOR] 질문 게시글 신고하기 중복 방지

src/main/java/org/example/tackit/config/FreeTagInitializer.java, src/main/java/org/example/tackit/config/QnATagInitializer.java
=> feat:#87-tag 데이터 추가

src/main/java/org/example/tackit/config/SecurityConfig.java
> #83
* 프론트 url 추가
* ec2 재배포 부탁드립니다 :D
=> [FEAT] cors 추가

src/main/java/org/example/tackit/domain/Free_board/Free_post/repository/FreePostJPARepository.java, src/main/java/org/example/tackit/domain/admin/repository/AdminFreePostRepository.java, src/main/java/org/example/tackit/domain/admin/repository/AdminQnAPostRepository.java, src/main/java/org/example/tackit/domain/admin/repository/AdminTipPostRepository.java, src/main/java/org/example/tackit/domain/admin/service/AdminFreePostService.java, src/main/java/org/example/tackit/domain/admin/service/AdminQnAPostService.java, src/main/java/org/example/tackit/domain/admin/service/AdminTipPostService.java, src/main/java/org/example/tackit/domain/mypage/service/MyPageFreeService.java
>#92
* 비활성화 게시글 조회 시 신고횟수가 3회 이상이면서 상태가 INACTIVE인 글들만 조회
* '내가 쓴 글' 불러올 때 Status가 ACTIVE인 것만 조회
=> [Fix] 관리자 및 마이페이지 에러 수정

src/main/java/org/example/tackit/config/TipTagInitializer.java, src/main/java/org/example/tackit/domain/Tip_board/Tip_post/controller/TipController.java, src/main/java/org/example/tackit/domain/Tip_board/Tip_post/dto/request/TipPostCreateDTO.java, src/main/java/org/example/tackit/domain/Tip_board/Tip_post/dto/request/TipPostUpdateDTO.java, src/main/java/org/example/tackit/domain/Tip_board/Tip_post/dto/response/TipPostDTO.java, src/main/java/org/example/tackit/domain/Tip_board/Tip_post/repository/TipMemberJPARepository.java, src/main/java/org/example/tackit/domain/Tip_board/Tip_post/repository/TipPostJPARepository.java, src/main/java/org/example/tackit/domain/Tip_board/Tip_post/repository/TipPostReportRepository.java, src/main/java/org/example/tackit/domain/Tip_board/Tip_post/repository/TipScrapRepository.java, src/main/java/org/example/tackit/domain/Tip_board/Tip_post/service/TipService.java, src/main/java/org/example/tackit/domain/Tip_board/Tip_post/service/TipTagService.java, src/main/java/org/example/tackit/domain/Tip_board/Tip_tag/controller/TipTagController.java, src/main/java/org/example/tackit/domain/Tip_board/Tip_tag/dto/response/TipTagPostResponseDto.java, src/main/java/org/example/tackit/domain/Tip_board/Tip_tag/dto/response/TipTagResponseDto.java, src/main/java/org/example/tackit/domain/Tip_board/Tip_tag/repository/TipPostTagMapRepository.java, src/main/java/org/example/tackit/domain/Tip_board/Tip_tag/repository/TipTagCustomRepository.java, src/main/java/org/example/tackit/domain/Tip_board/Tip_tag/repository/TipTagCustomRepositoryImpl.java, src/main/java/org/example/tackit/domain/Tip_board/Tip_tag/repository/TipTagRepository.java, src/main/java/org/example/tackit/domain/Tip_board/Tip_tag/service/TipTagService.java, src/main/java/org/example/tackit/domain/entity/TipPost.java, src/main/java/org/example/tackit/domain/entity/TipTag.java, src/main/java/org/example/tackit/domain/entity/TipTagMap.java, src/main/java/org/example/tackit/domain/mypage/service/MyPageTipService.java
> #94 
* 선임자의 TIP 게시판 태그 기능 추가
=> feat:#94-tip 게시판 태그 기능 추가

src/main/java/org/example/tackit/config/Redis/RedisUtil.java, src/main/java/org/example/tackit/config/jwt/TokenProvider.java, src/main/java/org/example/tackit/domain/auth/login/service/CustomUserDetailsService.java
=> [FIX] 탈퇴하기 재로그인 불가

src/main/java/org/example/tackit/domain/auth/login/dto/SignUpDto.java, src/main/java/org/example/tackit/domain/auth/login/service/AuthService.java
Reverts SookmyungTackit/backend#100
=> Revert "[FIX] 입사년도 대신 역할로 전달로 수정"

buildspec.yml
> #112 
* 테스트 옵션 없이 빌드하도록 임시 수정
=> refactor: buildspec.yml의 commands 수정

build.gradle, src/main/java/org/example/tackit/config/S3/S3Config.java, src/main/java/org/example/tackit/config/S3/S3Controller.java, src/main/java/org/example/tackit/config/S3/S3UploadService.java, src/main/java/org/example/tackit/config/SecurityConfig.java, src/main/java/org/example/tackit/domain/Free_board/Free_post/controller/FreePostController.java, src/main/java/org/example/tackit/domain/Free_board/Free_post/dto/request/FreePostReqDto.java, src/main/java/org/example/tackit/domain/Free_board/Free_post/dto/request/UpdateFreeReqDto.java, src/main/java/org/example/tackit/domain/Free_board/Free_post/dto/response/FreePostRespDto.java, src/main/java/org/example/tackit/domain/Free_board/Free_post/repository/FreePostImageRepository.java, src/main/java/org/example/tackit/domain/Free_board/Free_post/service/FreePostService.java, src/main/java/org/example/tackit/domain/entity/FreePost.java, src/main/java/org/example/tackit/domain/entity/FreePostImage.java, src/main/java/org/example/tackit/domain/entity/QnAPost.java, src/main/java/org/example/tackit/domain/entity/QnAPostImage.java, src/main/java/org/example/tackit/domain/entity/TipPost.java, src/main/java/org/example/tackit/domain/entity/TipPostImage.java, src/main/resources/application.properties
> #116 
* 자유게시판
* 이미지 포함 글 작성 구현
* 이미지 포함 글 수정 구현
=> [FEAT] 자유게시판 이미지 포함 글 작성, 수정 구현

src/main/java/org/example/tackit/domain/Free_board/Free_post/service/FreePostService.java, src/main/java/org/example/tackit/domain/QnA_board/QnA_post/controller/QnAPostController.java, src/main/java/org/example/tackit/domain/QnA_board/QnA_post/dto/request/QnAPostRequestDto.java, src/main/java/org/example/tackit/domain/QnA_board/QnA_post/dto/request/UpdateQnARequestDto.java, src/main/java/org/example/tackit/domain/QnA_board/QnA_post/dto/response/QnAPostResponseDto.java, src/main/java/org/example/tackit/domain/QnA_board/QnA_post/service/QnAPostService.java, src/main/java/org/example/tackit/domain/entity/QnAPost.java, src/main/java/org/example/tackit/domain/entity/QnAPostImage.java, src/main/java/org/example/tackit/domain/entity/TipPost.java
> #116 
<자유>
* 게시글 전체 조회 - 사진 포함 응답
* 게시글 상세 조회 - 사진 포함 응답
< 질문 >
* 신입 글 작성 - 사진 업로드
* 신입 글 수정 - 사진 수정 가능
* 게시글 전체 조회 - 사진 포함 응답
* 게시글 상세 조회 - 사진 포함 응답
=> [FEAT] 질문 게시판 ) 글 CRUD 사진 추가
